networks:
  frontend:
    driver: bridge
    internal: false  # For Streamlit access
  backend:
    driver: bridge
    internal: true   # For DB and internal services

volumes:
  timescaledb_data:
    name: timescaledb_data

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    networks:
      - backend
    ports:
      - "127.0.0.1:5432:5432"  # Only allow local connections
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    env_file: ../.env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    user: postgres:postgres
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
