name: Render Notebook

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for gh-pages branch creation

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-eda.txt

      - name: Convert and execute notebook
        run: |
          # Convert .py to .ipynb
          jupytext --to notebook eda/yandex-reviews-eda.py
          
          # Execute the notebook
          jupyter nbconvert --to notebook --execute eda/yandex-reviews-eda.ipynb --output executed-notebook.ipynb
          mv executed-notebook.ipynb eda/yandex-reviews-eda.ipynb

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Create or switch to gh-pages branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf .
          fi

      - name: Copy files to gh-pages
        run: |
          # Create necessary directories
          mkdir -p data eda
          
          # Copy files from main branch
          git checkout main -- data/* eda/yandex-reviews-eda.py eda/yandex-reviews-eda.ipynb
          
          # Stage changes
          git add data/* eda/yandex-reviews-eda.py eda/yandex-reviews-eda.ipynb

      - name: Commit and push changes
        run: |
          git commit -m "chore: update rendered notebook from main@${GITHUB_SHA}"
          git push origin gh-pages
