name: Render Notebook

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger from GitHub Actions UI

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for gh-pages branch creation
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-eda.txt

      - name: Download dataset and prepare files
        run: |
          # Create data directory
          mkdir -p data
          
          # Download dataset
          wget -O data/geo-reviews-dataset-2023.tskv https://github.com/yandex/geo-reviews-dataset-2023/raw/refs/heads/master/geo-reviews-dataset-2023.tskv
          
          # Convert .py to .ipynb
          jupytext --to notebook eda/yandex-reviews-eda.py
          
          # Execute the notebook
          cd eda
          jupyter nbconvert --to notebook --execute yandex-reviews-eda.ipynb --output executed-notebook.ipynb
          mv executed-notebook.ipynb yandex-reviews-eda.ipynb
          cd ..

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Save notebook files
        run: |
          # Create temp directory and save files
          mkdir -p /tmp/notebook-files/eda
          cp eda/yandex-reviews-eda.py eda/yandex-reviews-eda.ipynb /tmp/notebook-files/eda/

      - name: Create or switch to gh-pages branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git rm -rf .
          fi

      - name: Copy files to gh-pages
        run: |
          # Create necessary directories
          mkdir -p eda
          
          # Copy files from temp directory
          cp -r /tmp/notebook-files/eda/* eda/
          
          # Stage changes (exclude *.tskv and large files)
          git add eda/yandex-reviews-eda.py eda/yandex-reviews-eda.ipynb

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit -m "chore: update rendered notebook from main@${GITHUB_SHA}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin gh-pages
